apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "team8-app.fullname" . }}
  labels:
    {{- include "team8-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "team8-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "team8-app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "team8-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: app
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: {{ .Values.app.containerPort | default 8080 }}
              protocol: TCP
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  key: DATABASE_URL
                  name: backend
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  key: DB_PORT
                  name: backend
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: DB_USER
                  name: backend
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: backend
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  key: DB_NAME
                  name: backend
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  key: DB_NAME
                  name: backend
            - name: DB_DRIVER_NAME
              valueFrom:
                secretKeyRef:
                  key: DB_DRIVER_NAME
                  name: backend


          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- $paa := .Values.podAntiAffinity | default dict -}}
      {{- if or ($paa.enabled | default false) .Values.affinity }}
      affinity:
        {{- if ($paa.enabled | default false) }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: {{ include "team8-app.name" . }}
              topologyKey: {{ $paa.topologyKey | default "kubernetes.io/hostname" }}
        {{- end }}
        {{- with .Values.affinity }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
