{{- if .Values.vault.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-team8
    kind: SecretStore
  target:
    name: db-credentials
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: {{ .Values.vault.envPath | quote }}
        property: DB_HOST
    - secretKey: DB_PORT
      remoteRef:
        key: {{ .Values.vault.envPath | quote }}
        property: DB_PORT
    - secretKey: DB_USER
      remoteRef:
        key: {{ .Values.vault.envPath | quote }}
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.vault.envPath | quote }}
        property: DB_PASSWORD
    - secretKey: DB_NAME
      remoteRef:
        key: {{ .Values.vault.envPath | quote }}
        property: DB_NAME
    - secretKey: DB_DRIVER_NAME
      remoteRef:
        key: {{ .Values.vault.envPath | quote }}
        property: DB_DRIVER_NAME
{{- end }}
