{{- $dr := .Values.app.destinationRule }}
{{- if $dr.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "demo-app.fullname" . }}
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
spec:
  host: {{ include "demo-app.fullname" . }}
  trafficPolicy:
    {{- with $dr.trafficPolicy.connectionPool }}
    connectionPool:
      {{- with .http }}
      http:
        {{- if hasKey . "http1MaxPendingRequests" }}
        http1MaxPendingRequests: {{ .http1MaxPendingRequests }}
        {{- end }}
        {{- if hasKey . "maxRequestsPerConnection" }}
        maxRequestsPerConnection: {{ .maxRequestsPerConnection }}
        {{- end }}
      {{- end }}
    {{- end }}
    {{- with $dr.trafficPolicy.outlierDetection }}
    outlierDetection:
      {{- if hasKey . "consecutive5xxErrors" }}
      consecutive5xxErrors: {{ .consecutive5xxErrors }}
      {{- end }}
      {{- if hasKey . "interval" }}
      interval: {{ .interval }}
      {{- end }}
      {{- if hasKey . "baseEjectionTime" }}
      baseEjectionTime: {{ .baseEjectionTime }}
      {{- end }}
      {{- if hasKey . "maxEjectionPercent" }}
      maxEjectionPercent: {{ .maxEjectionPercent }}
      {{- end }}
    {{- end }}
{{- end }}
