apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: team8-app-db
  namespace: team8-ns
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: vault-team8
  target:
    name: db-credentials
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: kv/data/team8/backend
        property: DB_HOST
    - secretKey: DB_PORT
      remoteRef:
        key: kv/data/team8/backend
        property: DB_PORT
    - secretKey: DB_USER
      remoteRef:
        key: kv/data/team8/backend
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: kv/data/team8/backend
        property: DB_PASSWORD
    - secretKey: DB_NAME
      remoteRef:
        key: kv/data/team8/backend
        property: DB_NAME
    - secretKey: DB_DRIVER_NAME
      remoteRef:
        key: kv/data/team8/backend
        property: DB_DRIVER_NAME
    - secretKey: HF_TOKEN
      remoteRef:
        key: kv/data/team8/hf
        property: hf_token

