apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: team8-app-hf
  namespace: team8-ns
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: vault-team8
  target:
    name: hf-credentials
    creationPolicy: Owner
  data:
    - secretKey: HF_TOKEN
      remoteRef:
        key: kv/data/team8/hf
        property: hf_token
