apiVersion: apps/v1
kind: Deployment
metadata:
  name: team8-frontend
  labels:
    {{- include "team8-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "team8-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "team8-app.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "team8-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: frontend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.containerPort | default 80 }}
              protocol: TCP
          env:
            {{- with .Values.frontend.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- $paa := .Values.podAntiAffinity | default dict -}}
      {{- if or ($paa.enabled | default false) .Values.affinity }}
      affinity:
        {{- if ($paa.enabled | default false) }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: {{ include "team8-app.name" . }}
              topologyKey: {{ $paa.topologyKey | default "kubernetes.io/hostname" }}
        {{- end }}
        {{- with .Values.affinity }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
