{{- if .Values.istioIngress.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.istioIngress.gateway.name | default (printf "%s-gateway" (include "demo-app.fullname" .)) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
spec:
  selector:
    istio: ingress
  servers:
    {{- if .Values.istioIngress.redirectHttpToHttps }}
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        {{- range .Values.istioIngress.hosts }}
        - {{ . | quote }}
        {{- end }}
      tls:
        httpsRedirect: true
    {{- end }}

    {{- if .Values.istioIngress.tls.enabled }}
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        {{- range .Values.istioIngress.hosts }}
        - {{ . | quote }}
        {{- end }}
      tls:
        mode: SIMPLE
        credentialName: {{ .Values.istioIngress.tls.secretName }}
    {{- end }}
{{- end }}
