{{- if .Values.istioIngress.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "demo-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
spec:
  hosts:
    {{- range .Values.istioIngress.hosts }}
    - {{ . | quote }}
    {{- end }}
  gateways:
    - {{ .Values.istioIngress.gateway.name | default (printf "%s-gateway" (include "demo-app.fullname" .)) }}
  http:
    - route:
        - destination:
            host: {{ include "demo-app.fullname" . }}
            port:
              number: {{ .Values.service.port }}
{{- end }}
