apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-team8
spec:
  provider:
    vault:
      server: https://vault.kubepractice.ru
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: team8-ns
          serviceAccountRef:
            name: {{ include "team8-app.serviceAccountName" . }}
