apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-team8
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    vault:
      server: "https://vault.kubepractice.ru"
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "vault-team8"
          serviceAccountRef:
            name: {{ include "team8-app.serviceAccountName" . }}
