apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    {{- include "team8-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.serviceBackend.type }}
  ports:
    - port: {{ .Values.serviceBackend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "team8-app.selectorLabels" . | nindent 4 }}
