apiVersion: v1
kind: Service
metadata:
  name: front
spec:
  selector:
    app: front
  ports:
    - name: front
      port: 4173
      targetPort: 4173
    - name: controller
      port: 4173
      targetPort: 4173
  type: ClusterIP