{{- if .Values.vault.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-team8
spec:
  provider:
    vault:
      server: {{ .Values.vault.server | quote }}
      path: {{ .Values.vault.kvMount | quote }}
      version: {{ .Values.vault.kvVersion | quote }}
      auth:
        kubernetes:
          mountPath: {{ .Values.vault.kubernetesAuthMount | quote }}
          role: {{ .Values.vault.role | quote }}
          serviceAccountRef:
            name: {{ include "team8-app.serviceAccountName" . }}
{{- end }}
