{{- if .Values.worker.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "demo-worker.fullname" . }}
  labels:
    {{- include "demo-worker.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.worker.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "demo-worker.selectorLabels" . | nindent 6 }}
{{- end }}
