{{- if .Values.worker.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "demo-worker.fullname" . }}
  labels:
    {{- include "demo-worker.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "demo-worker.fullname" . }}
  minReplicaCount: {{ .Values.worker.keda.minReplicas }}
  maxReplicaCount: {{ .Values.worker.keda.maxReplicas }}
  pollingInterval: {{ .Values.worker.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.worker.keda.cooldownPeriod }}
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: {{ .Values.worker.keda.bootstrapServers | quote }}
        topic: {{ .Values.worker.keda.topic | quote }}
        consumerGroup: {{ .Values.worker.keda.consumerGroup | quote }}
        lagThreshold: "{{ .Values.worker.keda.lagThreshold }}"
        activationLagThreshold: "1"
{{- end }}
