apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "team8-app.fullname" . }}-keda-reader
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "demo-worker.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "team8-app.fullname" . }}-keda-reader
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "demo-worker.labels" . | nindent 4 }}
rules:
  - apiGroups: ["keda.sh"]
    resources: ["scaledobjects", "scaledjobs", "triggerauthentications"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "team8-app.fullname" . }}-keda-reader
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "demo-worker.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "team8-app.fullname" . }}-keda-reader
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "team8-app.fullname" . }}-keda-reader
